baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'lgbtqia.space community'
theme = "hugo-book"

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'


[params]
  BookTheme = 'auto'
  BookSection = 'docs'   
  BookRepo = 'https://github.com/alex-shpak/hugo-book'
  BookSearch = false
  BookComments = false